# version of docker-compose syntax
version: "3.0"

services:
  app:
    #build the docker image in the current directory
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    # volumes maps folder in the system with the docker internal directory system
    volumes:
      - ./app:/app
    # Command that is used to run the service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"